version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: acioli_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./includes/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - acioli_network

  php:
    build: .
    container_name: acioli_php
    restart: always
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - mysql
    networks:
      - acioli_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: acioli_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - acioli_network

volumes:
  mysql_data:

networks:
  acioli_network:
    driver: bridge